POST http://localhost:3333/instrumento
Content-Type: application/json

{

    "instru": "Bateria RMV",
    "marca": "RMV",
    "tipo": "2 pratos",
    "cor": "Preta"
}

###

GET http://localhost:3333/instrumento

###

GET http://localhost:3333/instrumento?search=IFMS


###
PUT http://localhost:3333/instrumentos/7c6f99f1-e7ae-4187-af4a-bcf6c9eb66c6
Content-Type: application/json

{
    "instru": "Bateria Premium",
    "marca": "Premium",
    "tipo": "5 pratos",
    "cor": "Azul"
}

###

DELETE http://localhost:3333/instrumentos/88bf6164-81bc-42f4-8659-9c74cc61250e
